Depend on jmoby-dashboard 1.1.0-taverna-1 to avoid
NoClassDefFoundError: org/biomoby/shared/MobySecondaryData
 at
org.biomoby.service.dashboard.data.ParametersTable$ParametersTableModel.<ini
t>(ParametersTable.java:298)

(The jmoby-dasboard 1.1.0-taverna, where ParametersTable lives, does not have a dependency back to jmoby and MobySecondaryData)

git-svn-id: http://taverna.googlecode.com/svn/taverna/engine/net.sf.taverna.t2.activities/trunk/biomoby-activity@7191 bf327186-88b3-11dd-a302-d386e5130c1c